// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyncratgmagwenohtour.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5bmNyYXRnbWFnd2Vub2h0b3VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MDQyODAsImV4cCI6MjA1OTI4MDI4MH0.SLfmJHLKFaRoWzo1SS5uKHzjhZJBY7YtWA3ASAkb4K4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);